# Generated by Django 5.2.1 on 2025-05-25 20:21

import django.db.models.deletion
import django.utils.timezone
import Backend.facturas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_emision', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=11)),
                ('cedula_cliente', models.CharField(max_length=11, validators=[Backend.facturas.models.validar_cedula_rif])),
                ('numero_factura', models.PositiveIntegerField()),
                ('productos', models.JSONField(help_text="Lista de productos con cantidad, nombre y precio_unitario. Ejemplo: [{'nombre': 'Producto A', 'cantidad': 2, 'precio_unitario': 10.5}]")),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'numero_factura')},
            },
        ),
    ]
