# Generated by Django 5.2.1 on 2025-05-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_producto_remove_factura_productos_factura_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
