# Generated by Django 5.2.1 on 2025-05-26 21:29

import django.db.models.deletion
import Backend.facturas.models.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_remove_factura_productos_delete_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='factura',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='factura',
            name='cedula_cliente',
            field=models.CharField(max_length=12, validators=[Backend.facturas.models.models.validar_cedula_rif]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.DateField(validators=[Backend.facturas.models.models.validar_fecha_emision]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='telefono_cliente',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='facturas.factura')),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='numero_factura',
        ),
    ]
