# Generated by Django 5.2.1 on 2025-05-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_alter_factura_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
