# Generated by Django 5.2.1 on 2025-07-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_alter_factura_iva_alter_factura_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='emitida',
            field=models.BooleanField(default=False),
        ),
    ]
