# Generated by Django 5.2.1 on 2025-05-26 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('segundo_nombre', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('primer_apellido', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('segundo_apellido', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('documento_identidad', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('J', 'Jurídico'), ('G', 'Gubernamental'), ('P', 'Pasaporte')], max_length=1)),
                ('numero_identidad', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener números.', regex='^\\d+$')])),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('contrasena_inicial', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Usuario', 'Usuario')], max_length=20)),
            ],
        ),
    ]
