# Generated by Django 5.2.1 on 2025-05-27 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0006_alter_factura_iva_alter_factura_subtotal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden_entrega', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lugar_emision', models.CharField(editable=False, max_length=100)),
                ('nombre_cliente', models.CharField(editable=False, max_length=100)),
                ('telefono_cliente', models.CharField(editable=False, max_length=11)),
                ('cedula_cliente', models.CharField(editable=False, max_length=11)),
                ('factura_afectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad_entregada', models.PositiveIntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='orden_de_entrega.ordendeentrega')),
            ],
        ),
    ]
