# Generated by Django 5.2.1 on 2025-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_entrega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeentrega',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordendeentrega',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordendeentrega',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productoentrega',
            name='monto_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
