# Generated by Django 5.2.4 on 2025-07-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_entrega', '0002_ordendeentrega_iva_ordendeentrega_subtotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendeentrega',
            name='emitida',
            field=models.BooleanField(default=False),
        ),
    ]
