# Generated by Django 5.2.1 on 2025-05-26 19:39

import django.db.models.deletion
import django.utils.timezone
import notas_de_debito_credito.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0002_producto_remove_factura_productos_factura_productos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar_emision', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('telefono_cliente', models.CharField(max_length=11)),
                ('cedula_cliente', models.CharField(max_length=11, validators=[notas_de_debito_credito.models.validar_cedula_rif])),
                ('numero_nota_debito', models.CharField(max_length=20, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('factura_afectada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptoDebito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nota_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='notas_de_debito_credito.notadebito')),
            ],
        ),
    ]
