# Generated by Django 5.2.1 on 2025-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas_de_debito_credito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notadebito',
            name='cedula_cliente',
            field=models.CharField(editable=False, max_length=11),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='fecha_emision',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='lugar_emision',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='nombre_cliente',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='notadebito',
            name='telefono_cliente',
            field=models.CharField(editable=False, max_length=11),
        ),
    ]
